## CI - Player And Plugin Tests
name: Player And Plugin Tests
run-name: Player And Plugin Tests

on:
  pull_request:
    branches:
      - "*"

jobs:
  notification:
    uses: kaltura/ovp-pipelines-pub/.github/workflows/notification.yaml@master
    secrets:
      PLAYER_MSTEAMS_WEBHOOK: ${{ secrets.PLAYER_MSTEAMS_WEBHOOK }}
  running-tests:
    uses: kaltura/ovp-pipelines-pub/.github/workflows/player_tests.yaml@master
    with:
      yarn-run-to-execute: 'eslint flow test'

