## CI/CD
name: Canary Full Flow
run-name: Canary Full Flow

on:
  push:
    branches:
      - master

jobs:
  canary-full-flow:
    if: github.event.pull_request.merged == true
    uses: kaltura/ovp-pipelines-pub/.github/workflows/player_cicd.yaml@master
    secrets:
      PLAYER_CENTRAL_ACCOUNT_ID: ${{ secrets.PLAYER_CENTRAL_ACCOUNT_ID }}
      PLAYER_SERVICES_ACCOUNT_ID: ${{ secrets.PLAYER_SERVICES_ACCOUNT_ID }}
      PLAYER_S3_BUCKET_DEPLOYMENT: ${{ secrets.PLAYER_S3_BUCKET_DEPLOYMENT }}
      PLAYER_S3_BUCKET_APPS: ${{ secrets.PLAYER_S3_BUCKET_APPS }}
      PLAYER_NPM_TOKEN: ${{ secrets.PLAYER_NPM_TOKEN }}
      PLAYER_LAMBDA_NAME: ${{ secrets.PLAYER_LAMBDA_NAME }}
      PLAYER_MSTEAMS_WEBHOOK: ${{ secrets.PLAYER_MSTEAMS_WEBHOOK }}
      PLAYER_GITHUB_BOT_TOKEN: ${{ secrets.PLAYER_GITHUB_BOT_TOKEN }}
    with:
      type: "plugin"
      stage: "canary"
      schema-type: "playerV3Versions"
      tests-yarn-run-to-execute: 'eslint flow test'
<<<<<<< HEAD

<<<<<<< Updated upstream
=======
>>>>>>> ae110530ea72bc5f2a074692eafbd35099c79849
=======

>>>>>>> Stashed changes
