## CI - Player And Plugin Tests
name: Player And Plugin Tests
run-name: Player And Plugin Tests

on:
  push:
    branches:
      - "devops-deployment"

jobs:
  running-tests:
    uses: kaltura/ovp-pipelines-pub/.github/workflows/player_tests.yaml@fix-uiconf-deploy
    secrets:
      PLAYER_MSTEAMS_WEBHOOK: ${{ secrets.PLAYER_MSTEAMS_WEBHOOK }}
    with:
      yarn-run-to-execute: 'eslint flow test'

